### ISSUE TITLE
Installed python modules are not loaded when using python3 instead of /usr/bin/python3 as Interpreter

### ISSUE THREAD

**Issue by ThatRandomDude** [rundeck-plugins/py-winrm-plugin#90]
I have the same problem mentioned in: #82 but after the merge of #89 i can't change the path to the interpreter.
Going back to 2.0.15 and setting the full path to python3 fixes the problem even for 2.1.0.
Then i can't change the config if i need to because it sets the wrong python path again.

In my opinion there are two possible solutions:

1. Revert the change so that it is possible to set the path again
2. Implement better control which python libraries are loaded for each copier/executor

OS: Debian 11 (Bullseye)
Rundeck: 4.8.0
py-winrm-plugin: 2.1.0

Best regards

**Comment by cconkrig** [comment]
@qualman any advice on this? We are seeing this across the board for ALL clients (ours are all Ubuntu 20.04 and 22.04). We've even setup brand new servers and it will not work using the documentation on the rundeck website. Reverting to prior to your PR and setting the interpreter correctly with the full /usr/bin/python3 path fixes the issue.  If you manage to jam the config in prior to the upgrade, it works until the latest version then just fails every window job.

**Comment by cconkrig** [comment]
Leaving this here for the next guy...  For all of my installs, this was a problem with how Rundeck sources the python3 modules with the rundeck user (I say this because if the interpreter was allowed to be /usr/bin/python3, everything worked, just forcing python3 even though it's the only one installed doesn't work in RD but works from the cli as the rundeck user). It's very bizarre that it ignores the system-installed packages. You can see them installed in pip (under root and rundeck users), you can see them installed with apt. I tried everything from setting /etc/enviornment with a $PYTHONPATH, etc. Running the winrm-check.py script by hand works fine as the rundeck user on the command line. I spent several hours tonight digging into the code and finally started force reinstalling all python3 packages. Once they were force-reinstalled pywinrm node executor started working. Here's what I ended up doing to fix it. No idea why this doesn't work with a fresh server.

These steps seemed to have worked:
===============================================================================
1.) as root: "pip3 install pywinrm[credssp] --force"
    1a.) This blew up with a long list of tracebacks (AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK')
    1b.) After awhile digging on vague Google threads, I found that I needed to delete the OpenSSL library module.  It was recommended to do the following: "rm -rf /usr/lib/python3/dist-packages/OpenSSL", I ran it... no issues.

2.) as root:  "apt reinstall python3-pip"  - figured might as well... can't hurt

3.) as root: "pip3 install -U pyopenssl" - Google said to do this... after doing the rm -rf command above

4.) as root:  "pip3 install pywinrm[credssp] --force"  - this time it installed correctly and seems to have bumped the version to 2.0.0 (previously 1.2.0), even though it was reporting it was installed and up to date just moments ago.
     4b.) Tried rundeck... no dice.  Still says to run pip install pywinrm[credssp]

5.) As rundeck user:  "pip3 install pywinrm[credssp] --force"
     5b.) Tried rundeck... it ran successfully.
    
Why?? No clue.  Hope that saves someone hours of wasted time...

**Comment by ThatRandomDude** [comment]
53d90f4 fixed this problem for me
